Web/FoodSpot.Web/Controllers/RecipesController.cs
namespace FoodSpot.Web.Controllers
{
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    using FoodSpot.Data.Models;
    using FoodSpot.Services.Data;
    using FoodSpot.Services.Messaging;
    using FoodSpot.Web.ViewModels.Ingredients;
    using FoodSpot.Web.ViewModels.Recipes;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class RecipesController : BaseController
    {
        private readonly ICategoriesService categoriesService;
        private readonly IRecipesService recipesService;
        private readonly IVotesService votesService;
        private readonly IIngredientsService ingredientsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IEmailSender emailSender;

        public RecipesController(
            ICategoriesService categoriesService,
            IRecipesService recipesService,
            IVotesService votesService,
            IIngredientsService ingredientsService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment webHostEnvironment,
            IEmailSender emailSender)
        {
            this.categoriesService = categoriesService;
            this.recipesService = recipesService;
            this.votesService = votesService;
            this.ingredientsService = ingredientsService;
            this.userManager = userManager;
            this.webHostEnvironment = webHostEnvironment;
            this.emailSender = emailSender;
        }

        [HttpGet("Recipes/All/{id:int}")]
        public IActionResult All(int id)
        {
            var recipesCount = this.recipesService.RecipesCount();

            var itemsPerPage = 4;

            var viewModel = new AllRecipesViewModel
            {
                Recipes = this.recipesService.AllToList<RecipeViewModel>(id, itemsPerPage),
                CurrentPage = id,
                RecipesCount = recipesCount,
                MaxPage = recipesCount % itemsPerPage == 0 ?
                            recipesCount / itemsPerPage :
                            (recipesCount / itemsPerPage) + 1,
            };

            if (id > viewModel.MaxPage)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new RecipeInputModel
            {
                Categories = this.categoriesService.GetCategoresAsSelectListItems(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(RecipeInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = this.categoriesService.GetCategoresAsSelectListItems();

                return this.View(model);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            await this.recipesService.CreateAsync(model, user.Id, this.webHostEnvironment.WebRootPath);

            return this.RedirectToAction("All", new { id = 1 });
        }

        [HttpGet("Recipes/{id:int}")]
        public IActionResult Recipe(int id)
        {
            var model = this.recipesService.GetRecipeById<SingleRecipeViewModel>(id);

            if (model is null)
            {
                return this.NotFound();
            }

            model.AverageVote = this.votesService.GetAverageVote(id);

            return this.View(model);
        }

        [HttpGet("Recipes/Edit/{id:int}")]
        [Authorize]
        public IActionResult Edit(int id)
        {
            var model = this.recipesService.GetRecipeById<RecipeEditModel>(id);

            model.Categories = this.categoriesService.GetCategoresAsSelectListItems();

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, RecipeEditModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = this.categoriesService.GetCategoresAsSelectListItems();

                return this.View(model);
            }

            await this.recipesService.UpdateAsync(id, model);

            return this.RedirectToAction("Recipe", new { id });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            await this.recipesService.DeleteAsync(id);

            return this.RedirectToAction("All", new { id = 1 });
        }

        public IActionResult Search()
        {
            var model = new IngredientListViewModel
            {
                Ingredients =
                    this.ingredientsService.All<SingleIngredientViewModel>().
                        OrderBy(x => x.Name),
            };

            return this.View(model);
        }

        public IActionResult Result(IngredientsListInputModel input)
        {
            if (input.Ingredients is null)
            {
                return this.RedirectToAction("Search");
            }

            var recipesCount = this.recipesService.RecipesResultCount(input.Ingredients);

            var part = 1;

            var itemsPerPart = 4;

            var viewModel = new RecipeListViewModel
            {
                Recipes =
                    this.recipesService.ResultList<RecipeViewModel>(input.Ingredients, part, itemsPerPart),
                TotalParts = recipesCount % itemsPerPart == 0 ?
                            recipesCount / itemsPerPart :
                            (recipesCount / itemsPerPart) + 1,
                TotalRecipes = recipesCount,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SendToEmail(int id)
        {
            var recipe = this.recipesService.GetRecipeById<SingleRecipeViewModel>(id);
            var html = new StringBuilder();
            html.AppendLine($"<h1>{recipe.Name}</h1>");
            html.AppendLine($"<h3>{recipe.UserUserName}</h3>");

            await this.emailSender.SendEmailAsync(
                "dsmarkov1@gmail.com",
                "FoodSpot",
                "siyoy31774@zcai77.com",
                recipe.Name,
                html.ToString());

            return this.RedirectToAction(nameof(this.Recipe), new { id });
        }

        public IActionResult LoadMore(Part part)
        {
            var itemsPerPart = 4;

            var viewModel = new RecipeListViewModel
            {
                Recipes =
                    this.recipesService.ResultList<RecipeViewModel>(part.Ingredients, part.Value, itemsPerPart),                
            };

            return this.PartialView("_PartingPartial", viewModel);
        }
    }
}

Web/FoodSpot.Web/Views/Shared/_Layout.cshtml
@using FoodSpot.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-dark border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <a class="navbar-brand text-white font-italic font-weight-bolder" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-pizza-slice fa-lg"></i> @GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <a class="nav-link text-white" asp-area="" asp-controller="Recipes" asp-action="All" asp-route-id="1"><i class="fas fa-book fa-lg"></i> All recipes</a>
                        </li>
                        <li>
                            <a class="nav-link text-white" asp-area="" asp-controller="Recipes" asp-action="Search"><i class="fas fa-search fa-lg"></i> Detailed search</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a class="nav-link text-white" asp-area="" asp-controller="Recipes" asp-action="Create"><i class="far fa-plus-square fa-lg"></i> Create Recipe</a>
                            </li>
                        }
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Administration" asp-controller="Recipes" asp-action="Index" asp-route-id="1"><i class="fas fa-cogs fa-lg"></i> Recipes Administration</a>
                            </li>
                        }
                        </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-white text-center">
        <div class="container">
            Copyright &copy; @DateTime.Now.Year - @GlobalConstants.SystemName
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/89bddd5b6d.js" crossorigin="anonymous"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/FoodSpot.Web/Views/Shared/_PagingPartial.cshtml
@model FoodSpot.Web.ViewModels.Recipes.RecipesPagingViewModel

<h4 class="text-black text-center mb-4"> Page @Model.CurrentPage of @Model.MaxPage</h4>
<hr />
<nav aria-label="Page navigation">
    <ul class="pagination pagination-lg justify-content-center">
        <li class="page-item @(Model.CurrentPage >= 2 ? string.Empty : "disabled")">
            <a class="page-link" asp-action="All" asp-route-id="@(Model.CurrentPage - 1)">Previous</a>
        </li>

        @for (int i = Model.CurrentPage - 3; i < Model.CurrentPage; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }

        <li class="page-item active" aria-current="page">
            <a class="page-link">
                @Model.CurrentPage
                <span class="sr-only">(current)</span>
            </a>
        </li>

        @for (int i = Model.CurrentPage + 1; i <= Model.CurrentPage + 3; i++)
        {
            if (i <= Model.MaxPage)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }

        <li class="page-item @(Model.CurrentPage < Model.MaxPage ? string.Empty : "disabled")">
            <a class="page-link" asp-action="All" asp-route-id="@(Model.CurrentPage + 1)">Next</a>
        </li>
    </ul>
</nav>

Web/FoodSpot.Web/Views/Shared/_PartingPartial.cshtml
@model FoodSpot.Web.ViewModels.Recipes.RecipeListViewModel 


@foreach (var recipe in Model.Recipes)
{
    <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
            <img class="card-img-top" src="~/images/@recipe.Image"
                 asp-append-version="true" alt="@recipe.Name">
            <div class="card-body">
                <h4 class="card-title">
                    <img src="~/images/@recipe.CategoryImage" style="width:30px; height:auto" /> @recipe.Name
                </h4>
                <p class="card-text">@recipe.Instructions</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary btn-lg" asp-controller="Recipes" asp-action="Recipe" asp-route-id="@recipe.Id">See more</a>
            </div>
        </div>
    </div>
}